INSERT INTO `menu_restaurant`(`id`, `name`, `price`, `type`, `restaurant_id`) VALUES
            ('1','classic burrito','9','main course','1'),
            ('2','power burrito','13','main course','1'),
            ('3','chicken burrito','12','main course','1'),
            ('4','salad','4','appetizer','1'),
            ('5','bruschetta','6','appetizer','1'),
            ('6','mango salad','4','appetizer','1'),
            ('7','ice cream','4','dessert','1'),
            ('8','chocolate mousse','5','dessert','1'),
            ('9','cake','3','dessert','1'),
            ('10','pepsi','2.50','drink','1'),
            ('11','cola','1.50','drink','1'),
            ('12','corona','3.50','drink','1'),
            ('13','margherita pizza','8','main course','2'),
            ('14','pizza prosciutto','14','main course','2'),
            ('15','quattro formaggi pizza','13','main course','2'),
            ('16','carpaccio','5','appetizer','2'),
            ('17','caponata','4','main course','2'),
            ('18','baked goat cheese dip','7','main course','2'),
            ('19','cheesecake','9','dessert','2'),
            ('20','gelato','4','dessert','2'),
            ('21','fondant chocolate','5','dessert','2'),
            ('22','pepsi','3','drink','2'),
            ('23','red wine','5','drink','2'),
            ('24','white wine','5','drink','2'),
            ('25','spaghetti bolognese','7.50','main course','3'),
            ('26','pasta carbonara','9.50','main course','3'),
            ('27','Lasagna','11.50','main course','3'),
            ('28','caprese salad','4.50','appetizer','3'),
            ('29','ultimate antipasto platter','5.50','appetizer','3'),
            ('30','marinated olives','2.50','appetizer','3'),
            ('31','gelato','4.50','dessert','3'),
            ('32','fondant chocolate','5.50','dessert','3'),
            ('33','tiramisu','4.50','dessert','3'),
            ('34','red wine','4.50','drink','3'),
            ('35','hertog jan','3.50','drink','3'),
            ('36','cola','2.50','drink','3')
